// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> initTokenizer({required List<int> tokenizerJson}) => RustLib
    .instance
    .api
    .crateApiTokenizerInitTokenizer(tokenizerJson: tokenizerJson);

Future<TokenizedInput> tokenize({required String text}) =>
    RustLib.instance.api.crateApiTokenizerTokenize(text: text);

class TokenizedInput {
  final Int64List inputIds;
  final Int64List attentionMask;

  const TokenizedInput({required this.inputIds, required this.attentionMask});

  @override
  int get hashCode => inputIds.hashCode ^ attentionMask.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenizedInput &&
          runtimeType == other.runtimeType &&
          inputIds == other.inputIds &&
          attentionMask == other.attentionMask;
}
